namespace SAOTRPG.Items;

// Static citation database for ALL Legendary weapons. Keyed by DefinitionId.
// Source: LEGENDARY_REDISTRIBUTION_PROPOSAL.md §5 (Bundle 11/12 anchor table).
// 184/185 coverage (1 gap: stone-craft corrupted variants excluded per Bundle 11 §10).
public static class CanonCitationData
{
    public readonly record struct Citation(string Source, string FloorAnchor, string Detail);

    private static readonly Dictionary<string, Citation> _entries = new()
    {
        // ── One-Handed Sword ─────────────────────────────────────────
        ["elucidator"] = new("SAO LN vol 4 (canon)", "F50 floor-boss",
            "Kirito takes Elucidator from F50 boss \"The Gleam Eyes\"."),
        ["dark_repulser"] = new("SAO LN vol 2 / HF (canon)", "F55 field-boss",
            "Lisbeth-forged white blade gifted to Kirito on F55."),
        ["remains_heart"] = new("LN/IF (canon)", "F48 Lisbeth quest",
            "Lisbeth character-quest reward — relocated from R6 craft."),
        ["savage_squall"] = new("Invented (AL Lycoris-style)", "F17 floor-boss",
            "AincradTRPG floor-boss original drop."),
        ["void_eater"] = new("Invented", "F30 floor-boss",
            "AincradTRPG floor-boss original drop."),
        ["eurynomes_holy_sword"] = new("Hollow Fragment (canon)", "F90 NPC quest",
            "High Priestess Sola implement quest, F90 — HF endgame."),
        ["fiendblade_deathbringer"] = new("Hollow Fragment (canon)", "F81 NPC quest",
            "Ranger Torva implement quest — HF F81 canon."),
        ["fayblade_tizona"] = new("Hollow Fragment (canon)", "F83 NPC quest",
            "Apiarist Nell implement quest — HF F83 canon."),
        ["godblade_dragonslayer"] = new("Hollow Fragment (canon)", "F85 field-boss",
            "Abased Beast field-boss drop — HF F85 canon."),
        ["ohs_rosso_forneus"] = new("Integral Factor (canon)", "F61 field-boss",
            "Crimson Forneus IF Series boss drop — Rosso quartet."),
        ["ohs_yasha_astaroth"] = new("Integral Factor (canon)", "F87 field-boss",
            "Yasha IF Series boss drop."),
        ["ohs_gaou_reginleifr"] = new("Integral Factor (canon)", "F90 field-boss",
            "Gaou IF Series boss drop."),
        ["ohs_aurumbrand_hauteclaire"] = new("Hollow Fragment (canon)", "F92 NPC quest",
            "Auric Knight Halric implement quest — HF F92."),
        ["ohs_velocious_brain"] = new("Hollow Fragment (canon)", "F80–F86 chest",
            "HF F82 Hollow Area implement floor band."),
        ["ohs_unfolding_truth_fragrant_olive"] = new("Alicization / SAO MD (canon)", "F65 NPC quest",
            "Selka chain reward — SAO MD-Alicization arc canon."),
        ["ohs_elucidator_rouge"] = new("Last Recollection / FD (canon)", "F98 field-boss",
            "Ashen Kirito Simulacrum drop — LR red-edge canon."),
        ["ohs_blade_of_the_lightwolf"] = new("Invented (AL Lycoris)", "F77–F83 chest",
            "AL Lycoris invented brand — non-canon Aincrad."),
        ["ohs_illustrious_sword"] = new("Invented (AL DLC)", "F79–F85 chest",
            "AL DLC invented blade — non-canon."),
        ["celestial_blade"] = new("Invented (IM-style shop tier)", "F88–F92 shop tier",
            "AincradTRPG shop-tier capstone — non-canon Aincrad."),
        ["liberator"] = new("SAO LN — Kirito orphan blade (canon)", "F56–F60 chest",
            "LN flavor weapon, post-Dark Repulser era."),
        ["final_avalanche"] = new("Norse myth — chain T3", "F45–F50 chain",
            "Tyrfing chain T3 mythic crafting anchor."),
        ["ohs_variable_v_vice"] = new("Hollow Fragment / LR (canon)", "R6 craft",
            "HF/LR R6 Lisbeth craft — Lindarth F48 access."),
        ["ohs_liberator_astral_legion"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["ohs_marginless_blade"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["ohs_red_rose_sword"] = new("Last Recollection (canon)", "F95 field-boss",
            "Warden of Blooming Rose drop — LR Kirito's red-rose pair."),
        ["ohs_black_iron_dual_sword_a"] = new("Alicization arc (canon)", "F78–F84 chest",
            "Underworld Kirito's early-arc black-iron blade (lead)."),
        ["ohs_black_iron_dual_sword_b"] = new("Alicization arc (canon)", "F78–F84 chest",
            "Underworld Kirito's offhand black-iron blade (mirror)."),
        ["ohs_sword_of_diva"] = new("SAO Memory Defrag (canon)", "F70–F76 chest",
            "MD original — Diva collab anchor band."),
        ["ohs_chaos_raider_dual"] = new("Fractured Daydream (canon)", "F86–F92 chest",
            "FD Character Core dual-blade — chaos raider variant."),
        ["ohs_golden_osmanthus"] = new("Fractured Daydream / Alice (canon)", "F74–F80 chest",
            "Alice Synthesis Thirty FD core — golden-osmanthus motif."),
        ["ohs_tanquiem"] = new("Fractured Daydream / Oberon (canon)", "F70–F76 chest",
            "Oberon FD core — ALO Fairy King relic."),
        ["ohs_silvery_ruler"] = new("Fractured Daydream / Administrator (canon)", "F97 field-boss",
            "Administrator's Regent drop — Quinella FD core."),
        ["ohs_scorching_blade"] = new("Invented", "F69–F75 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["ohs_double_edged_blade"] = new("Invented", "F71–F77 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["ohs_dragoncrest"] = new("Invented", "F84–F90 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["ohs_blazing_sword"] = new("Lost Song (canon)", "F66–F72 chest",
            "LS Salamander mid-game blade — canon ALO."),
        ["ohs_rainbow_blade_ex_eterna"] = new("Last Recollection DLC (canon)", "F90–F95 chest",
            "LR DLC apex blade — rainbow ex-eterna motif."),

        // ── Two-Handed Sword ─────────────────────────────────────────
        ["saintblade_durandal"] = new("Hollow Fragment (canon) / myth", "F87 field-boss",
            "Night Stalker drop — HF canon, named after Roland's blade."),
        ["stigmablade_arondight"] = new("Hollow Fragment (canon) / myth", "F95 field-boss",
            "Gaia Breaker drop — Arondight (Lancelot's blade) myth name."),
        ["demonblade_gram"] = new("Hollow Fragment (canon) / Norse myth", "F96 field-boss",
            "Eternal Dragon drop — Gram is Sigurd's dragonslaying sword."),
        ["ths_sacred_cross"] = new("Infinity Moment (canon)", "F92 floor-boss LAB",
            "IM F92 LAB-floor canon drop."),
        ["ths_wice_ritter"] = new("IF/IM (canon)", "F86–F92 shop tier",
            "Infinity Moment shop-tier canon weapon."),
        ["ths_demonslayer"] = new("Invented (AL Lycoris)", "F82–F88 chest",
            "AL Lycoris invented brand."),
        ["celestial_greatsword"] = new("Invented (IM-style shop tier)", "F94–F98 shop tier",
            "AincradTRPG shop-tier capstone — non-canon."),
        ["ifrit"] = new("Arabic myth — chain T3", "F50–F58 chain",
            "Ascalon chain T3 mythic crafting anchor."),
        ["demonblade_crimson_stream"] = new("Invented", "F40 floor-boss",
            "AincradTRPG floor-boss original drop."),
        ["ths_saintblade_ragnarok"] = new("Hollow Fragment (canon) / Norse myth", "F92–F98 chest",
            "HF F95 Hollow Area lock zone — Ragnarok end-times motif."),
        ["ths_absoludia_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["ths_ogreblade_over_the_cross"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["ths_deliverer_majestic_lord"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["ths_ambitious_juggernaut"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["ths_sword_of_causality"] = new("SAO Memory Defrag (canon)", "F62–F68 chest",
            "MD original — causality-themed greatsword."),
        ["ths_flame_lord"] = new("Fractured Daydream / Heathcliff (canon)", "F80 field-boss",
            "Pyre Lord drop — Heathcliff FD core flame motif."),
        ["ths_blazewyrm_greatsword"] = new("Invented", "F75–F82 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["ths_purgatorial_greatsword"] = new("Invented (AL DLC)", "F86–F92 chest",
            "AL DLC invented brand — non-canon."),
        ["ths_lifestream_greatsword"] = new("Invented", "F88–F94 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["ths_object_eraser"] = new("Last Recollection myth (canon)", "F89–F95 chest",
            "LR apex armor-pierce greatsword."),

        // ── Katana ───────────────────────────────────────────────────
        ["jato_onikirimaru"] = new("Hollow Fragment (canon)", "F80 NPC quest",
            "Hunter Kojiro implement quest — HF F80 canon."),
        ["shinto_ama_no_murakumo"] = new("Hollow Fragment / Shinto myth", "F95 NPC quest",
            "Elder Beastkeeper quest — Susanoo's cloud-splitter blade."),
        ["yato_masamune"] = new("Hollow Fragment (canon)", "F98 field-boss",
            "Blaze Armor drop — HF Hollow Area canon."),
        ["kat_muramasa"] = new("Infinity Moment (canon) / myth", "F90–F94 shop tier",
            "IM canon shop-tier — named after the cursed-blade smith."),
        ["kat_saku"] = new("Infinity Moment (canon)", "F94 floor-boss LAB",
            "IM F94 LAB-floor canon drop."),
        ["kat_demon_blade_muramasa"] = new("Lost Song (canon)", "F65–F72 chest",
            "LS canon Salamander apex katana."),
        ["midnight_sun"] = new("Invented", "F49 floor-boss",
            "AincradTRPG floor-boss original."),
        ["celestial_katana"] = new("Invented (IM-style shop tier)", "F89–F93 shop tier",
            "AincradTRPG shop-tier capstone — non-canon."),
        ["shichishito"] = new("Japanese myth — chain T3", "F55–F62 chain",
            "Masamune chain T3 — seven-branched sword anchor."),
        ["kat_yasha_oratorio"] = new("Integral Factor (canon)", "F85–F90 chest",
            "Yasha IF Series chest band — anchored near Yasha boss F87."),
        ["kat_gaou_oratorio"] = new("Integral Factor (canon)", "F88–F94 chest",
            "Gaou IF Series chest band — anchored near Gaou boss F90."),
        ["kat_burning_haze_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["kat_godslayer_tattered_hope"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["kat_avidya_samsara_blade"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["kat_shining_nemesisz"] = new("SAO Memory Defrag (canon)", "F66–F72 chest",
            "MD original — Nemesis collab katana."),
        ["kat_murasama_g4_dual"] = new("Fractured Daydream / Kirito (canon)", "F88–F94 chest",
            "Kirito FD core — Murasama G4 dual-wield variant."),
        ["kat_spirit_kagutsuchi"] = new("Fractured Daydream / Klein (canon)", "F60 field-boss",
            "Kagutsuchi the Fire Samurai drop — Klein FD core fire spirit."),
        ["kat_spirit_susanoo"] = new("Fractured Daydream / Klein (canon)", "F70 field-boss",
            "Susanoo the Storm Blade drop — Klein FD core storm spirit."),
        ["kat_futsu_no_mitama"] = new("Lost Song / Shinto myth", "F60–F66 chest",
            "Shinto spirit-blade of Futsunushi — LS canon mid-game."),
        ["kat_darkness_rending_blade"] = new("Last Recollection (canon)", "F84–F90 chest",
            "LR canon darkness-rending katana."),

        // ── Rapier ───────────────────────────────────────────────────
        ["mothers_rosario"] = new("SAO LN — Mother's Rosario arc", "F76 NPC quest",
            "Yuuki canon — given to Asuna in the MR arc."),
        ["rap_rosso_rhapsody"] = new("Integral Factor (canon)", "F58–F64 chest",
            "Rosso quartet IF chest band, anchored at F61 boss."),
        ["rap_spiralblade_rendering_fail"] = new("Hollow Fragment (canon)", "F84 NPC quest",
            "Spiralist Vey implement quest — HF F84."),
        ["rap_glimmerblade_banishing_ray"] = new("Hollow Fragment (canon)", "F93 field-boss",
            "Banishing Ray drop — HF F93."),
        ["midnight_rain"] = new("Invented", "F43 floor-boss",
            "AincradTRPG floor-boss original."),
        ["celestial_rapier"] = new("Invented (IM-style shop tier)", "F91–F95 shop tier",
            "AincradTRPG shop-tier capstone — non-canon."),
        ["lambent_light"] = new("SAO LN (canon)", "F40 NPC-gift",
            "Asuna's signature rapier — KoB-era F40 LN canon."),
        ["charadrios"] = new("Greek myth — chain T3", "F45–F52 chain",
            "Hexagramme chain T3 mythic crafting anchor."),
        ["radiant_light"] = new("SAO LN (canon)", "F88–F94 chest",
            "LN postgame Asuna — successor blade to Lambent Light."),
        ["rap_ishvalca_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["rap_championfoil_radiant_chariot"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["rap_glimmerspine_silver_bullet"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["rap_noctis_strasse"] = new("Infinity Moment (canon)", "F84–F90 shop tier",
            "IM canon shop-tier rapier — anchor F86."),
        ["rap_espada_of_sword_dance"] = new("SAO Memory Defrag (canon)", "F60–F66 chest",
            "MD original — sword-dance theme rapier."),
        ["rap_macafitel"] = new("Fractured Daydream / Yuuki (canon)", "F85 field-boss",
            "Yuuki's Echo drop — Yuuki FD core, MR arc canon."),
        ["rap_graceful_needle"] = new("Invented", "F86–F92 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["rap_glaring_light"] = new("Lost Song (canon)", "F77–F83 chest",
            "LS canon high-tier rapier — light motif."),

        // ── Axe ──────────────────────────────────────────────────────
        ["axe_ground_gorge"] = new("Hollow Fragment (canon)", "F55 NPC quest",
            "Agil's Apprentice quest reward — HF canon."),
        ["ragnaroks_bane_headsman"] = new("Hollow Fragment (canon) / Norse myth", "F94 field-boss",
            "Ark Knight drop — HF F94 canon."),
        ["axe_rosso_dominion"] = new("Integral Factor (canon)", "F58–F64 chest",
            "Rosso quartet IF — anchored at F61."),
        ["axe_crusher_bond_cyclone"] = new("Hollow Fragment (canon)", "F85 NPC quest",
            "Crusher Drago implement quest — HF F85."),
        ["axe_fellaxe_demons_scythe"] = new("Hollow Fragment (canon)", "F86 field-boss",
            "Fellaxe Revenant drop — HF F86 canon."),
        ["celestial_axe"] = new("Invented (IM-style)", "F65–F72 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["nidhoggs_fang"] = new("Norse myth — chain T3", "F58–F65 chain",
            "Ouroboros chain T3 — Nidhogg dragonfang anchor."),
        ["axe_lord_burster_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["axe_hecatomb_giga_disaster"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["axe_ingurgitator_belzericht"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["axe_schwarzs_blitz"] = new("Infinity Moment (canon)", "F88–F94 shop tier",
            "IM canon shop-tier axe — anchor F90."),
        ["axe_northern_light"] = new("Infinity Moment (canon)", "F96 floor-boss LAB",
            "IM F96 LAB-floor canon drop."),
        ["axe_naz"] = new("Fractured Daydream / Agil (canon)", "F86–F92 chest",
            "Agil FD core — Naz axe variant."),
        ["axe_deathbringer"] = new("Invented", "F88–F94 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["axe_snowsunder"] = new("Invented", "F66–F72 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["axe_lang"] = new("Last Recollection / Lost Song (canon)", "F44–F48 chest",
            "LR/LS canon — Bundle 12 lifted to fill F44–47 gap."),
        ["axe_nadr"] = new("Last Recollection myth (canon)", "F73–F79 chest",
            "LR mythic axe — late mid-tier band."),

        // ── Mace ─────────────────────────────────────────────────────
        ["yggdrasil"] = new("Norse myth — chain T3", "F62–F68 chain",
            "Mjolnir chain T3 mythic crafting anchor."),
        ["mace_of_asclepius"] = new("Hollow Fragment / Greek myth", "F77 field-boss",
            "Goblin Leader drop — HF F77; Asclepius healer myth."),
        ["infinite_ouroboros"] = new("Hollow Fragment (canon)", "F79 NPC quest",
            "Scholar Ellroy quest — HF F79 implement."),
        ["starmace_elysium"] = new("Hollow Fragment (canon)", "F88 NPC quest",
            "Watcher Kael quest — HF F88 implement."),
        ["mce_caduceus"] = new("Lost Song / LR (canon)", "F70–F76 chest",
            "LS canon healer-staff motif."),
        ["cactus_bludgeon"] = new("Invented", "F38 floor-boss",
            "AincradTRPG floor-boss original."),
        ["celestial_mace"] = new("Invented (IM-style)", "F62–F68 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["mce_ijelfur_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["mce_dictators_punisher"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["mce_photon_hammer_xp_smasher"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["mce_grida_replicant"] = new("Fractured Daydream / Lisbeth (canon)", "F75–F81 chest",
            "Lisbeth FD core — Grida replicant hammer."),
        ["mce_starshatter"] = new("Invented", "F75–F81 chest",
            "AincradTRPG late mid-tier filler — non-canon."),
        ["mce_beasthowl"] = new("Invented", "F70–F76 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["mce_whirlpool_hammer"] = new("Invented", "F80–F86 chest",
            "AincradTRPG late-tier filler — non-canon."),

        // ── Spear ────────────────────────────────────────────────────
        ["vijaya"] = new("Indian myth — chain T3", "F60–F67 chain",
            "Caladbolg chain T3 mythic crafting anchor."),
        ["demonspear_gae_bolg"] = new("Hollow Fragment / Celtic myth", "F83 field-boss",
            "Arboreal Fear drop — HF F83; Cú Chulainn's spear."),
        ["saintspear_rhongomyniad"] = new("Hollow Fragment / Arthurian myth", "F91 NPC quest",
            "Torchbearer Meir quest — HF F91; Arthur's spear."),
        ["godspear_gungnir"] = new("Hollow Fragment / Norse myth", "F98 NPC quest",
            "Sentinel Captain quest — Odin's spear."),
        ["spr_lunatic_roof"] = new("Infinity Moment (canon)", "F98 floor-boss LAB",
            "IM F98 LAB-floor canon drop."),
        ["spr_wave_schneider"] = new("Infinity Moment (canon)", "F92–F96 shop tier",
            "IM canon shop-tier weapon."),
        ["spr_divine_laevateinn"] = new("LR / Norse myth", "F86–F92 chest",
            "Surtr's flame sword reimagined as polearm."),
        ["celestial_spear"] = new("Invented (IM-style shop tier)", "F93–F97 shop tier",
            "AincradTRPG shop-tier capstone — non-canon."),
        ["spr_rosso_sigrun"] = new("Integral Factor (canon)", "F58–F64 chest",
            "Rosso quartet IF chest band — anchored at F61 boss."),
        ["spr_asleigeon_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["spr_heavenslance_elpis_order"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["spr_arctic_pillar"] = new("Invented", "F78–F84 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["spr_frostpeak"] = new("Invented", "F84–F90 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["spr_brave_song"] = new("Lost Song (canon)", "F72–F78 chest",
            "LS canon Sylph apex spear — brave-song motif."),
        ["spr_elders_trident"] = new("Last Recollection myth (canon)", "F73–F79 chest",
            "LR mythic trident — elder-spirit motif."),

        // ── Dagger ───────────────────────────────────────────────────
        ["mate_chopper"] = new("LN / Integral Factor (canon)", "F1–F5 chest",
            "IF canon F1-area starter — \"Mate's Chopper\" anchor."),
        ["misericorde"] = new("Medieval myth — chain T3", "F50–F58 chain",
            "Iron Maiden chain T3 mythic crafting anchor."),
        ["dag_rue_feuille"] = new("Infinity Moment (canon)", "F94–F98 shop tier",
            "IM canon shop-tier dagger."),
        ["dag_mirage_knife"] = new("Infinity Moment (canon)", "F95 floor-boss LAB",
            "IM F95 LAB-floor canon drop."),
        ["dag_obsidian_dagger"] = new("Fractured Daydream (canon) / Yui", "F70–F76 chest",
            "Yui FD anchor band."),
        ["dag_thunder_gods_rift_blade"] = new("Fractured Daydream (canon) / Argo", "F78–F84 chest",
            "Argo FD anchor band."),
        ["dag_fragarach"] = new("LR / Celtic myth", "F76–F82 chest",
            "Lugh's wind-cutting blade."),
        ["phantasmagoria"] = new("Invented", "F24 floor-boss",
            "AincradTRPG floor-boss original."),
        ["celestial_dagger"] = new("Invented (IM-style)", "F70–F76 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["dag_yasha_envy"] = new("Integral Factor (canon)", "F85–F90 chest",
            "Yasha IF Series chest band — anchored near Yasha boss F87."),
        ["dag_genocide_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["dag_notes_end_trinity"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["dag_whitespark"] = new("Invented", "F86–F92 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["dag_giardino"] = new("Last Recollection myth (canon)", "F25–F47 chest",
            "LR mythic dagger — Bundle 12 widened to fill F44–47 gap."),

        // ── Bow ──────────────────────────────────────────────────────
        ["bow_zephyros"] = new("Infinity Moment (canon)", "F85 floor-boss LAB",
            "IM F85 LAB-floor canon drop."),
        ["bow_artemis"] = new("Infinity Moment (canon) / Greek myth", "F99 floor-boss LAB",
            "IM F99 LAB-floor — paired with Night Sky Divine."),
        ["bow_rosso_albatross"] = new("Integral Factor (canon)", "F58–F64 chest",
            "Rosso quartet IF chest band."),
        ["bow_silvan_bow"] = new("Lost Song (canon)", "F69–F75 chest",
            "LS canon Sylph apex bow."),
        ["bow_holy_larc_qui_ne_faut"] = new("Lost Song / LR myth", "F89–F95 chest",
            "LS canon mythic apex bow."),
        ["starfall"] = new("Invented", "F11 floor-boss",
            "AincradTRPG floor-boss original."),
        ["celestial_bow"] = new("Invented (IM-style shop tier)", "F96–F99 shop tier",
            "AincradTRPG shop-tier capstone — non-canon."),
        ["bow_cinder_bow"] = new("Invented", "F73–F79 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["bow_loveblight_bow"] = new("Invented", "F80–F86 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["bow_glitzwood_bow"] = new("Invented", "F84–F90 chest",
            "AincradTRPG late-tier filler — non-canon."),
        ["bow_artemis_fult"] = new("Last Recollection myth (canon)", "F73–F79 chest",
            "LR mythic bow — Artemis Fult variant."),

        // ── Scimitar ─────────────────────────────────────────────────
        ["iblis"] = new("Islamic myth — chain T3", "F45–F52 chain",
            "Satanachia chain T3 mythic crafting anchor."),
        ["sci_arcaneblade_soul_binder"] = new("Hollow Fragment (canon)", "F80 field-boss",
            "Soul Binder drop — HF F80 implement."),
        ["sci_fellblade_ruinous_doom"] = new("Hollow Fragment (canon)", "F83 field-boss",
            "Ruinous Herald drop — HF F83."),
        ["sci_deathglutton_epetamu"] = new("Hollow Fragment (canon)", "F99 NPC quest",
            "Last Herald Xiv quest — HF F99 apex implement."),
        ["sci_silver_wing"] = new("Infinity Moment (canon)", "F92–F96 shop tier",
            "IM canon shop-tier scimitar."),
        ["sci_glow_haze"] = new("Infinity Moment (canon)", "F93 floor-boss LAB",
            "IM F93 LAB-floor canon drop."),
        ["celestial_scimitar"] = new("Invented (IM-style)", "F65–F71 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["sci_saphir_avatar"] = new("Hollow Fragment Avatar (canon)", "F70+ avatar pool",
            "HF Avatar weapon — LAB drop, no fixed floor."),
        ["sci_crescentblade_original_sin"] = new("Hollow Fragment (canon)", "R6 craft",
            "HF R6 Lisbeth craft — Lindarth F48 access."),
        ["sci_savage_sandstorm"] = new("Invented", "F75–F81 chest",
            "AincradTRPG late mid-tier filler — non-canon."),

        // ── Shield (Legendary armor) ─────────────────────────────────
        ["shd_rosso_aegis"] = new("Integral Factor (canon)", "F61 field-boss",
            "Rosso secondary drop — IF Series boss."),
        ["shd_yasha_kavacha"] = new("Integral Factor (canon)", "F87 field-boss",
            "Yasha secondary drop — IF Series boss."),
        ["shd_gaou_tatari"] = new("Integral Factor (canon)", "F90 field-boss",
            "Gaou secondary drop — IF Series boss."),
        ["shd_ancile"] = new("LR / Roman myth", "F84–F90 chest",
            "Sacred shield of Mars — mythic chest band."),

        // ── Scythe ───────────────────────────────────────────────────
        ["celestial_scythe"] = new("Invented (IM-style)", "F70–F76 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["scy_eldark_radius_sigma"] = new("Last Recollection (canon)", "R6 craft",
            "LR canon scythe — Lisbeth R6 craft, Lindarth F48 access."),

        // ── Claws ────────────────────────────────────────────────────
        ["clw_iron_fist_oguma"] = new("Lost Song (canon)", "F77–F83 chest",
            "LS canon Salamander apex claws."),
        ["celestial_claws"] = new("Invented (IM-style)", "F66–F72 chest",
            "AincradTRPG mid-tier filler — non-canon."),
        ["clw_paopei"] = new("Last Recollection myth (canon)", "F73–F79 chest",
            "LR mythic claws — Chinese paopei treasure motif."),
    };

    // Look up a citation by definition id. Returns null when no canon entry exists —
    // caller falls back to "Invented for AincradTRPG" or "No canon citation available".
    public static Citation? Lookup(string? defId)
    {
        if (string.IsNullOrEmpty(defId)) return null;
        return _entries.TryGetValue(defId, out var c) ? c : null;
    }

    // Total registered citation count — used for documentation / coverage queries.
    public static int Count => _entries.Count;
}
