using SAOTRPG.Items;

namespace SAOTRPG.Systems;

// Reward delivery channel. Col grants currency; EquippableTitle adds to active-title pool;
// AutoPassive applies a permanent stat bump or subsystem flag; DisplayOnly grants nothing material.
public enum RewardType { Col, EquippableTitle, AutoPassive, DisplayOnly }

// Trigger evaluation channel. The MilestoneSystem dispatcher looks at TriggerType
// to know which event source / counter to compare against TriggerThreshold.
public enum TriggerType
{
    FirstEvent,
    KillCountTotal,
    KillCountByTag,
    KillCountBySpecies,
    FloorReached,
    LifeSkillLevel,
    BountyCompleted,
    LoreCollected,
    KarmaThreshold,
    BestiaryCount,
    LegendaryCollected,
    CollectableCount,
    QuestCompleted,
    GuildJoined,
    UniqueSkillUnlocked,
    AllyRecruited,
    DivineAwakened,
    Conditional,
}

// One canonical milestone entry. Id is the persistent unlock key (LifetimeStats.UnlockedMilestones).
// SubCategory currently only used by Collectables (bucket name); other categories leave it null.
public record Milestone(
    string Id,
    string Name,
    string Description,
    string Category,
    string? SubCategory,
    TriggerType Trigger,
    string? TriggerArg,
    int TriggerThreshold,
    RewardType Reward,
    int ColReward,
    StatType? BonusStat,
    int BonusValue,
    string? VsTag,
    bool SpoilerHidden);

// Read-only catalog of all milestones. Combines base 56 (achievements + titles + life-skill
// milestones) with canon imports, 184 Legendary collection entries, trigger-source-derived,
// and gap-filler entries. Total ~330.
public static class MilestoneRegistry
{
    public static readonly IReadOnlyList<Milestone> All = new Milestone[]
    {
        // ── Achievements (Combat) ───────────────────────────────────────
        new("first_kill", "First Blood", "Defeat your first monster",
            "Combat", null, TriggerType.FirstEvent, "first_kill", 1,
            RewardType.Col, 50, null, 0, null, false),
        new("first_boss", "Boss Slayer", "Defeat your first floor boss",
            "Combat", null, TriggerType.FirstEvent, "first_boss", 1,
            RewardType.Col, 200, null, 0, null, false),
        new("kills_100", "Centurion", "Defeat 100 monsters",
            "Combat", null, TriggerType.KillCountTotal, null, 100,
            RewardType.Col, 500, null, 0, null, false),
        new("kills_500", "Walking Calamity", "Defeat 500 monsters",
            "Combat", null, TriggerType.KillCountTotal, null, 500,
            RewardType.Col, 2500, null, 0, null, false),
        new("perfect_streak_5", "Untouchable", "Achieve a 5-kill perfect streak",
            "Combat", null, TriggerType.Conditional, "perfect_streak_5", 5,
            RewardType.Col, 300, null, 0, null, false),

        // ── Achievements (Floor) ────────────────────────────────────────
        new("floor_5", "Ascending", "Reach floor 5",
            "Floor", null, TriggerType.FloorReached, null, 5,
            RewardType.Col, 150, null, 0, null, false),
        new("floor_10", "Into the Unknown", "Reach floor 10",
            "Floor", null, TriggerType.FloorReached, null, 10,
            RewardType.Col, 300, null, 0, null, false),
        new("floor_25", "Veteran Climber", "Reach floor 25",
            "Floor", null, TriggerType.FloorReached, null, 25,
            RewardType.Col, 1000, null, 0, null, false),
        new("floor_50", "Halfway There", "Reach floor 50",
            "Floor", null, TriggerType.FloorReached, null, 50,
            RewardType.Col, 3000, null, 0, null, false),
        new("floor_100", "Apex of Aincrad", "Reach floor 100",
            "Floor", null, TriggerType.FloorReached, null, 100,
            RewardType.Col, 10000, null, 0, null, false),
        new("speed_clear", "Speed Demon", "Speed-clear a floor under par time",
            "Floor", null, TriggerType.Conditional, "speed_clear", 1,
            RewardType.Col, 200, null, 0, null, false),

        // ── Achievements (Discovery) ────────────────────────────────────
        new("all_lore", "Loremaster", "Discover all lore stones",
            "Discovery", null, TriggerType.LoreCollected, null, 1,
            RewardType.Col, 1500, null, 0, null, false),
        new("bounty_complete", "Bounty Hunter", "Complete a bounty contract",
            "Discovery", null, TriggerType.BountyCompleted, null, 1,
            RewardType.Col, 250, null, 0, null, false),
        new("survive_hemorrhage", "Iron Will", "Survive a hemorrhage combo",
            "Combat", null, TriggerType.Conditional, "survive_hemorrhage", 1,
            RewardType.Col, 400, null, 0, null, false),

        // ── Titles (Combat — species/tag/total kills) ───────────────────
        new("title_boar_slayer", "Boar Slayer",
            "+5% Attack vs beast (10 Frenzy Boar kills).",
            "Combat", null, TriggerType.KillCountBySpecies, "Frenzy Boar", 10,
            RewardType.EquippableTitle, 0, StatType.Attack, 2, "beast", false),
        new("title_beast_hunter", "Beast Hunter",
            "+5% Attack vs beast (100 beast kills).",
            "Combat", null, TriggerType.KillCountByTag, "beast", 100,
            RewardType.EquippableTitle, 0, StatType.Attack, 3, "beast", false),
        new("title_beast_lord", "Beast Lord",
            "+10% Attack vs beast (1000 beast kills).",
            "Combat", null, TriggerType.KillCountByTag, "beast", 1000,
            RewardType.EquippableTitle, 0, StatType.Attack, 6, "beast", false),
        new("title_nepent_cutter", "Nepent Cutter",
            "+3 Dexterity (10 Nepent kills).",
            "Combat", null, TriggerType.KillCountBySpecies, "Nepent", 10,
            RewardType.EquippableTitle, 0, StatType.Dexterity, 3, null, false),
        new("title_kobold_crusher", "Kobold Crusher",
            "+5% Attack vs humanoid (10 Kobold kills).",
            "Combat", null, TriggerType.KillCountBySpecies, "Kobold", 10,
            RewardType.EquippableTitle, 0, StatType.Attack, 2, "humanoid", false),
        new("title_titan_breaker", "Titan Breaker",
            "+3 Strength (10 Taurus kills).",
            "Combat", null, TriggerType.KillCountBySpecies, "Taurus", 10,
            RewardType.EquippableTitle, 0, StatType.Strength, 3, null, false),
        new("title_dragon_slayer", "Dragon Slayer",
            "+10% Attack vs dragon (100 dragon kills).",
            "Combat", null, TriggerType.KillCountByTag, "dragon", 100,
            RewardType.EquippableTitle, 0, StatType.Attack, 5, "dragon", false),
        new("title_dragon_lord", "Dragon Lord",
            "+20% Attack vs dragon (1000 dragon kills).",
            "Combat", null, TriggerType.KillCountByTag, "dragon", 1000,
            RewardType.EquippableTitle, 0, StatType.Attack, 10, "dragon", false),
        new("title_cardinal_breaker", "Cardinal Breaker",
            "+5 Intelligence (10 Cardinal Error kills).",
            "Combat", null, TriggerType.KillCountBySpecies, "Cardinal Error", 10,
            RewardType.EquippableTitle, 0, StatType.Intelligence, 5, null, false),
        new("title_hollow_walker", "Hollow Walker",
            "+5% Attack vs hollow (100 hollow kills).",
            "Combat", null, TriggerType.KillCountByTag, "hollow", 100,
            RewardType.EquippableTitle, 0, StatType.Attack, 3, "hollow", false),
        new("title_undead_exorcist", "Undead Exorcist",
            "+5% Attack vs undead (100 undead kills).",
            "Combat", null, TriggerType.KillCountByTag, "undead", 100,
            RewardType.EquippableTitle, 0, StatType.Attack, 3, "undead", false),
        new("title_insect_crusher", "Insect Crusher",
            "+3 Agility (100 insect kills).",
            "Combat", null, TriggerType.KillCountByTag, "insect", 100,
            RewardType.EquippableTitle, 0, StatType.Agility, 3, null, false),
        new("title_the_black_swordsman", "The Black Swordsman",
            "+10 Attack (9999 total kills). The title that needs no introduction.",
            "Combat", null, TriggerType.KillCountTotal, null, 9999,
            RewardType.EquippableTitle, 0, StatType.Attack, 10, null, false),
        new("title_survivor", "Survivor",
            "+10 MaxHP (reached Floor 50 without death).",
            "Combat", null, TriggerType.FloorReached, null, 50,
            RewardType.EquippableTitle, 0, StatType.Health, 10, null, false),
        new("title_beginner_slayer", "Beginner Slayer",
            "+1 to all core attributes (100 total kills).",
            "Combat", null, TriggerType.KillCountTotal, null, 100,
            RewardType.EquippableTitle, 0, StatType.Strength, 1, null, false),

        // ── Life Skill milestones (Sleep / Walking / Running / Eating /
        //    Bargaining / Swimming / Mining × 10/25/50/99) ───────────────
        new("life_sleep_10", "Sleep — Apprentice", "+5 MaxHP",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Sleep", 10,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_sleep_25", "Sleep — Adept", "+15 MaxHP",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Sleep", 25,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_sleep_50", "Sleep — Expert", "+35 MaxHP",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Sleep", 50,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_sleep_99", "Sleep — Master", "+80 MaxHP, faster HP regen",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Sleep", 99,
            RewardType.AutoPassive, 0, null, 0, null, false),

        new("life_walking_10", "Walking — Apprentice", "+2 Endurance",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Walking", 10,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_walking_25", "Walking — Adept", "+5 Endurance",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Walking", 25,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_walking_50", "Walking — Expert", "+10 Endurance",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Walking", 50,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_walking_99", "Walking — Master", "+20 Endurance",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Walking", 99,
            RewardType.AutoPassive, 0, null, 0, null, false),

        new("life_running_10", "Running — Apprentice", "+2 Speed",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Running", 10,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_running_25", "Running — Adept", "+5 Speed",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Running", 25,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_running_50", "Running — Expert", "+10 Speed",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Running", 50,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_running_99", "Running — Master", "+20 Speed, -30% sprint cost",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Running", 99,
            RewardType.AutoPassive, 0, null, 0, null, false),

        new("life_eating_10", "Eating — Apprentice", "+10% food potency",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Eating", 10,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_eating_25", "Eating — Adept", "+25% food potency",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Eating", 25,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_eating_50", "Eating — Expert", "+50% food potency",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Eating", 50,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_eating_99", "Eating — Master", "+100% food duration",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Eating", 99,
            RewardType.AutoPassive, 0, null, 0, null, false),

        new("life_bargaining_10", "Bargaining — Apprentice", "-3% buy / +3% sell",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Bargaining", 10,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_bargaining_25", "Bargaining — Adept", "-6% buy / +6% sell",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Bargaining", 25,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_bargaining_50", "Bargaining — Expert", "-10% buy / +10% sell",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Bargaining", 50,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_bargaining_99", "Bargaining — Master", "-15% buy / +15% sell (cap)",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Bargaining", 99,
            RewardType.AutoPassive, 0, null, 0, null, false),

        new("life_swimming_10", "Swimming — Apprentice", "Water at full speed",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Swimming", 10,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_swimming_25", "Swimming — Adept", "Deep water passable (slow)",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Swimming", 25,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_swimming_50", "Swimming — Expert", "Deep water at full speed",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Swimming", 50,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_swimming_99", "Swimming — Master", "Master swimmer",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Swimming", 99,
            RewardType.AutoPassive, 0, null, 0, null, false),

        new("life_mining_10", "Mining — Apprentice", "+5% ore drop chance",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Mining", 10,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_mining_25", "Mining — Adept", "+1 bonus ore roll (20%)",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Mining", 25,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_mining_50", "Mining — Expert", "Mithril +1 Adamant Trace; Iron costs -1 strike",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Mining", 50,
            RewardType.AutoPassive, 0, null, 0, null, false),
        new("life_mining_99", "Mining — Master", "+20% Divine vein drops; durability damage halved",
            "Life Skills", null, TriggerType.LifeSkillLevel, "Mining", 99,
            RewardType.AutoPassive, 0, null, 0, null, false),

        // ────────────────────────────────────────────────────────────────
        //   SAO Infinity Moment-era canon achievements (post-F75 bosses).
        //   IM-26 reuses existing floor_100 (Apex of Aincrad) — not duplicated.
        // ────────────────────────────────────────────────────────────────
        new("if_beater", "Beater",
            "Cleared the F1 prologue and accepted the burden of the front line.",
            "Story", null, TriggerType.FirstEvent, "tutorial_complete", 1,
            RewardType.Col, 100, null, 0, null, false),
        new("if_f76_boss", "Slayer of the Ghastlygaze", "Defeated the boss of Floor 76.",
            "Floor", null, TriggerType.FloorReached, null, 76,
            RewardType.Col, 1000, null, 0, null, true),
        new("if_f77_boss", "Slayer of the Crystalized Claw", "Defeated the boss of Floor 77.",
            "Floor", null, TriggerType.FloorReached, null, 77,
            RewardType.Col, 1000, null, 0, null, true),
        new("if_f78_boss", "Slayer of the Horn of Madness", "Defeated the boss of Floor 78.",
            "Floor", null, TriggerType.FloorReached, null, 78,
            RewardType.Col, 1000, null, 0, null, true),
        new("if_f79_boss", "Slayer of the Tempest Trihead", "Defeated the boss of Floor 79.",
            "Floor", null, TriggerType.FloorReached, null, 79,
            RewardType.Col, 1000, null, 0, null, true),
        new("if_f80_boss", "Slayer of the Guilty Scythe", "Defeated the boss of Floor 80.",
            "Floor", null, TriggerType.FloorReached, null, 80,
            RewardType.Col, 1500, null, 0, null, true),
        new("if_f81_boss", "Slayer of the Dark Knight", "Defeated the boss of Floor 81.",
            "Floor", null, TriggerType.FloorReached, null, 81,
            RewardType.Col, 1500, null, 0, null, true),
        new("if_f82_boss", "Slayer of the Grand Legacy", "Defeated the boss of Floor 82.",
            "Floor", null, TriggerType.FloorReached, null, 82,
            RewardType.Col, 1500, null, 0, null, true),
        new("if_f83_boss", "Slayer of the Furious Horn", "Defeated the boss of Floor 83.",
            "Floor", null, TriggerType.FloorReached, null, 83,
            RewardType.Col, 1500, null, 0, null, true),
        new("if_f84_boss", "Slayer of the Ant Queen", "Defeated the boss of Floor 84.",
            "Floor", null, TriggerType.FloorReached, null, 84,
            RewardType.Col, 1500, null, 0, null, true),
        new("if_f85_boss", "Slayer of the Maelstrom Trihead", "Defeated the boss of Floor 85.",
            "Floor", null, TriggerType.FloorReached, null, 85,
            RewardType.Col, 2000, null, 0, null, true),
        new("if_f86_boss", "Slayer of the Skeleton King", "Defeated the boss of Floor 86.",
            "Floor", null, TriggerType.FloorReached, null, 86,
            RewardType.Col, 2000, null, 0, null, true),
        new("if_f87_boss", "Slayer of the Radiance Eater", "Defeated the boss of Floor 87.",
            "Floor", null, TriggerType.FloorReached, null, 87,
            RewardType.Col, 2000, null, 0, null, true),
        new("if_f88_boss", "Slayer of the Rebellious Eyes", "Defeated the boss of Floor 88.",
            "Floor", null, TriggerType.FloorReached, null, 88,
            RewardType.Col, 2000, null, 0, null, true),
        new("if_f89_boss", "Slayer of the Murderer Fang", "Defeated the boss of Floor 89.",
            "Floor", null, TriggerType.FloorReached, null, 89,
            RewardType.Col, 2000, null, 0, null, true),
        new("if_f90_boss", "Slayer of the Blade Ruler", "Defeated the boss of Floor 90.",
            "Floor", null, TriggerType.FloorReached, null, 90,
            RewardType.Col, 2500, null, 0, null, true),
        new("if_f91_boss", "Slayer of the Absolute Gazer", "Defeated the boss of Floor 91.",
            "Floor", null, TriggerType.FloorReached, null, 91,
            RewardType.Col, 2500, null, 0, null, true),
        new("if_f92_boss", "Slayer of the Chaos Dragon", "Defeated the boss of Floor 92.",
            "Floor", null, TriggerType.FloorReached, null, 92,
            RewardType.Col, 2500, null, 0, null, true),
        new("if_f93_boss", "Slayer of the Lava Creeper", "Defeated the boss of Floor 93.",
            "Floor", null, TriggerType.FloorReached, null, 93,
            RewardType.Col, 2500, null, 0, null, true),
        new("if_f94_boss", "Slayer of the Blazing Knight", "Defeated the boss of Floor 94.",
            "Floor", null, TriggerType.FloorReached, null, 94,
            RewardType.Col, 2500, null, 0, null, true),
        new("if_f95_boss", "Slayer of the Genocide Eyes", "Defeated the boss of Floor 95.",
            "Floor", null, TriggerType.FloorReached, null, 95,
            RewardType.Col, 3000, null, 0, null, true),
        new("if_f96_boss", "Slayer of the Slaughter Fang", "Defeated the boss of Floor 96.",
            "Floor", null, TriggerType.FloorReached, null, 96,
            RewardType.Col, 3000, null, 0, null, true),
        new("if_f97_boss", "Slayer of the Death Emperor", "Defeated the boss of Floor 97.",
            "Floor", null, TriggerType.FloorReached, null, 97,
            RewardType.Col, 3000, null, 0, null, true),
        new("if_f98_boss", "Slayer of the Kaiser Dragon", "Defeated the boss of Floor 98.",
            "Floor", null, TriggerType.FloorReached, null, 98,
            RewardType.Col, 3000, null, 0, null, true),
        new("if_f99_boss", "Slayer of the Rulers of Hades", "Defeated the boss of Floor 99.",
            "Floor", null, TriggerType.FloorReached, null, 99,
            RewardType.Col, 4000, null, 0, null, true),
        new("if_last_attack_beta_tester", "Last-Attack Beta Tester",
            "Land the killing blow on 25 floor bosses.",
            "Combat", null, TriggerType.KillCountByTag, "last_attack_boss", 25,
            RewardType.EquippableTitle, 0, StatType.Attack, 5, "boss", true),
        new("if_no_ally_death", "The Shepherd",
            "Reached F100 without any party member falling.",
            "Story", null, TriggerType.Conditional, "no_ally_death_f100", 1,
            RewardType.EquippableTitle, 0, StatType.Vitality, 5, null, true),
        new("if_power_player", "Power Player", "Reach character Level 100.",
            "Combat", null, TriggerType.Conditional, "level_100", 100,
            RewardType.Col, 5000, null, 0, null, false),
        new("if_lisbeth_customer", "Lisbeth's Best Customer",
            "Successfully upgrade weapons 200 times.",
            "Equipment", null, TriggerType.KillCountByTag, "weapon_upgrades", 200,
            RewardType.Col, 2500, null, 0, null, false),

        // ────────────────────────────────────────────────────────────────
        //   SAO Re:Hollow Fragment-era canon achievements.
        // ────────────────────────────────────────────────────────────────
        new("hf_seatrees", "Slayer of the Sea of Trees",
            "Defeat the Hollow Area boss of Selvendys Forest.",
            "Story", null, TriggerType.QuestCompleted, "hollow_seatrees", 1,
            RewardType.Col, 2000, null, 0, null, true),
        new("hf_floatingruin", "Slayer of the Floating Ruin",
            "Defeat the boss of the Floating Ruin Hollow Area.",
            "Story", null, TriggerType.QuestCompleted, "hollow_floatingruin", 1,
            RewardType.Col, 2000, null, 0, null, true),
        new("hf_bay", "Slayer of the Bay Sentinel",
            "Defeat the boss of the coastal Hollow Area.",
            "Story", null, TriggerType.QuestCompleted, "hollow_bay", 1,
            RewardType.Col, 2000, null, 0, null, true),
        new("hf_void", "Slayer of the Great Void",
            "Defeat the boss of the endless-void Hollow Area.",
            "Story", null, TriggerType.QuestCompleted, "hollow_void", 1,
            RewardType.Col, 2500, null, 0, null, true),
        new("hf_outerworld", "Slayer of the Otherworld",
            "Defeat the boss of the Otherworld Hollow Area.",
            "Story", null, TriggerType.QuestCompleted, "hollow_outerworld", 1,
            RewardType.Col, 2500, null, 0, null, true),
        new("hf_control", "Slayer of the Control Spire",
            "Defeat the inner-system Hollow boss.",
            "Story", null, TriggerType.QuestCompleted, "hollow_control", 1,
            RewardType.Col, 3000, null, 0, null, true),
        new("hf_poh_slain", "The PoH-Slayer",
            "Defeat PoH, leader of Laughing Coffin.",
            "Combat", null, TriggerType.QuestCompleted, "poh_slain", 1,
            RewardType.EquippableTitle, 0, StatType.Attack, 5, "pker", true),
        new("hf_hollow_kirito", "The Mirror Slayer",
            "Defeat your hollow reflection.",
            "Canon", null, TriggerType.QuestCompleted, "hollow_kirito_slain", 1,
            RewardType.EquippableTitle, 0, StatType.Attack, 5, "hollow", true),
        new("hf_yuuki_duel", "The Absolute Sword",
            "Win the optional duel against Yuuki.",
            "Canon", null, TriggerType.QuestCompleted, "yuuki_duel_won", 1,
            RewardType.EquippableTitle, 0, StatType.Dexterity, 8, null, true),
        new("hf_tycoon", "Tycoon",
            "Save 1,000,000 Col across one run.",
            "Discovery", null, TriggerType.Conditional, "col_lifetime_1m", 1000000,
            RewardType.EquippableTitle, 0, StatType.Intelligence, 4, null, false),
        new("hf_element_researcher", "The Element Researcher",
            "Complete 100 Implement / Element Research quests.",
            "Discovery", null, TriggerType.Conditional, "implements_done", 100,
            RewardType.Col, 3000, null, 0, null, false),
        new("hf_debug_field_tester", "Debug-Class Field Tester",
            "Complete 80 Hollow Missions.",
            "Discovery", null, TriggerType.Conditional, "hollow_missions_done", 80,
            RewardType.Col, 2500, null, 0, null, false),

        // ────────────────────────────────────────────────────────────────
        //   Trigger-source-derived: guild joins, unique skills, allies,
        //   awakening, karma, quests.
        // ────────────────────────────────────────────────────────────────

        // Guild recruits.
        new("guild_kob", "Knight of Blood",
            "Joined the Knights of the Blood Oath.",
            "Story", null, TriggerType.GuildJoined, "KnightsOfBlood", 1,
            RewardType.EquippableTitle, 0, StatType.Defense, 4, null, false),
        new("guild_alf", "Liberation Vanguard",
            "Joined the Aincrad Liberation Force.",
            "Story", null, TriggerType.GuildJoined, "AincradLiberationForce", 1,
            RewardType.EquippableTitle, 0, StatType.Attack, 3, null, false),
        new("guild_fuurinkazan", "Fuurinkazan Companion",
            "Joined Klein's Fuurinkazan.",
            "Story", null, TriggerType.GuildJoined, "Fuurinkazan", 1,
            RewardType.EquippableTitle, 0, StatType.Strength, 3, null, false),
        new("guild_legend_braves", "Legend Brave",
            "Joined the Legend Braves.",
            "Story", null, TriggerType.GuildJoined, "LegendBraves", 1,
            RewardType.EquippableTitle, 0, StatType.Endurance, 3, null, false),
        new("guild_dda", "Dragon's Aide",
            "Joined the Divine Dragon Alliance.",
            "Story", null, TriggerType.GuildJoined, "DivineDragonAlliance", 1,
            RewardType.EquippableTitle, 0, StatType.Intelligence, 4, null, false),
        new("guild_sleeping_knights", "Sleeping Knight",
            "Joined the Sleeping Knights.",
            "Story", null, TriggerType.GuildJoined, "SleepingKnights", 1,
            RewardType.EquippableTitle, 0, StatType.Vitality, 4, null, false),
        new("guild_moonlit_black_cats", "Moonlit Companion",
            "Joined the Moonlit Black Cats.",
            "Story", null, TriggerType.GuildJoined, "MoonlitBlackCats", 1,
            RewardType.EquippableTitle, 0, StatType.Agility, 3, null, false),
        new("guild_laughing_coffin", "Coffin Initiate",
            "Sworn to Laughing Coffin's red banner.",
            "Story", null, TriggerType.GuildJoined, "LaughingCoffin", 1,
            RewardType.EquippableTitle, 0, StatType.Attack, 5, "human", true),

        // Unique skill unlocks.
        new("us_dual_blades", "Dual Blades Awakened",
            "Unlocked the Dual Blades unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "DualBlades", 1,
            RewardType.Col, 1500, null, 0, null, false),
        new("us_holy_sword", "Holy Sword Awakened",
            "Unlocked the Holy Sword unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "HolySword", 1,
            RewardType.Col, 1500, null, 0, null, false),
        new("us_martial_arts", "Martial Arts Awakened",
            "Unlocked the Martial Arts unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "MartialArts", 1,
            RewardType.Col, 1000, null, 0, null, false),
        new("us_katana_mastery", "Katana Mastery Awakened",
            "Unlocked the Katana Mastery unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "KatanaMastery", 1,
            RewardType.Col, 1000, null, 0, null, false),
        new("us_darkness_blade", "Darkness Blade Awakened",
            "Unlocked the Darkness Blade unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "DarknessBlade", 1,
            RewardType.Col, 1200, null, 0, null, false),
        new("us_blazing_edge", "Blazing Edge Awakened",
            "Unlocked the Blazing Edge unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "BlazingEdge", 1,
            RewardType.Col, 1200, null, 0, null, false),
        new("us_frozen_edge", "Frozen Edge Awakened",
            "Unlocked the Frozen Edge unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "FrozenEdge", 1,
            RewardType.Col, 1200, null, 0, null, false),
        new("us_extra_search", "Extra Search Awakened",
            "Unlocked the Extra Search unique skill.",
            "Canon", null, TriggerType.UniqueSkillUnlocked, "ExtraSearch", 1,
            RewardType.Col, 800, null, 0, null, false),

        // Ally recruits — TriggerArg matches Ally.Name.
        new("ally_klein", "Recruited Klein",
            "Klein joined your party.",
            "Story", null, TriggerType.AllyRecruited, "Klein", 1,
            RewardType.Col, 500, null, 0, null, false),
        new("ally_asuna", "Recruited Asuna",
            "Asuna joined your party.",
            "Story", null, TriggerType.AllyRecruited, "Asuna", 1,
            RewardType.Col, 500, null, 0, null, false),
        new("ally_agil", "Recruited Agil",
            "Agil joined your party.",
            "Story", null, TriggerType.AllyRecruited, "Agil", 1,
            RewardType.Col, 500, null, 0, null, false),

        // Divine awakenings.
        new("first_awakening", "First Awakening",
            "Awakened your first Divine weapon to ◈1.",
            "Equipment", null, TriggerType.DivineAwakened, "first", 1,
            RewardType.Col, 1500, null, 0, null, false),
        new("first_lv3_awakening", "Awakening Master",
            "Awakened a weapon to ◈3.",
            "Equipment", null, TriggerType.DivineAwakened, "lv3", 3,
            RewardType.Col, 3000, null, 0, null, false),

        // Karma threshold milestones.
        new("karma_saint", "Saint",
            "Reached Honorable karma (+50). +5% prices in friendly towns.",
            "Karma", null, TriggerType.KarmaThreshold, "ge", 50,
            RewardType.EquippableTitle, 0, StatType.Vitality, 3, null, false),
        new("karma_outlaw", "Outlaw",
            "Fell to Outlaw karma (-50). +10% drop chance from all kills.",
            "Karma", null, TriggerType.KarmaThreshold, "le", -50,
            RewardType.EquippableTitle, 0, StatType.Attack, 4, null, false),
        new("karma_atonement", "Atonement",
            "Recovered from Outlaw to Neutral karma.",
            "Karma", null, TriggerType.Conditional, "atonement", 1,
            RewardType.Col, 1500, null, 0, null, false),
        new("karma_town_guard_kill", "Criminal",
            "Killed a Town of Beginnings Guard.",
            "Karma", null, TriggerType.Conditional, "town_guard_killed", 1,
            RewardType.Col, 0, null, 0, null, false),

        // Quest completions — major canon storylines.
        new("quest_mothers_rosario", "Mother's Rosario",
            "Completed Yuuki's final quest.",
            "Story", null, TriggerType.QuestCompleted, "mothers_rosario", 1,
            RewardType.EquippableTitle, 0, StatType.Vitality, 5, null, true),
        new("quest_swords_awakening", "Sword's Awakening",
            "Completed the Sword's Awakening quest line.",
            "Story", null, TriggerType.QuestCompleted, "swords_awakening", 1,
            RewardType.Col, 2000, null, 0, null, false),
        new("quest_heaven_piercing", "Heaven-Piercing Blade",
            "Completed the Heaven-Piercing Blade quest.",
            "Story", null, TriggerType.QuestCompleted, "heaven_piercing", 1,
            RewardType.Col, 2000, null, 0, null, false),
        new("quest_first_quest", "Quest Initiate",
            "Turned in your first quest.",
            "Story", null, TriggerType.QuestCompleted, "_first_quest", 1,
            RewardType.Col, 100, null, 0, null, false),

        // ────────────────────────────────────────────────────────────────
        //   Death-category gap-fillers — fired from PlayerDiedDetailed.
        //   Persisted via LifetimeStats so a triggering death is recorded.
        // ────────────────────────────────────────────────────────────────
        new("first_death", "First Death",
            "Suffered your first defeat.",
            "Death", null, TriggerType.FirstEvent, "first_death", 1,
            RewardType.Col, 100, null, 0, null, false),
        new("death_poison", "Poisoned",
            "Killed by venom in your veins.",
            "Death", null, TriggerType.FirstEvent, "death_poison", 1,
            RewardType.Col, 50, null, 0, null, false),
        new("death_bleeding", "Hemorrhaged",
            "Bled out from a wound that never closed.",
            "Death", null, TriggerType.FirstEvent, "death_bleeding", 1,
            RewardType.Col, 50, null, 0, null, false),
        new("death_starvation", "Starved",
            "Died with an empty stomach and emptier larder.",
            "Death", null, TriggerType.FirstEvent, "death_starvation", 1,
            RewardType.Col, 50, null, 0, null, false),
        new("death_trap", "Pitfall",
            "Killed by a trap.",
            "Death", null, TriggerType.FirstEvent, "death_trap", 1,
            RewardType.Col, 50, null, 0, null, false),
        new("death_burning", "Immolated",
            "Killed by burns.",
            "Death", null, TriggerType.FirstEvent, "death_burning", 1,
            RewardType.Col, 50, null, 0, null, false),
        new("death_lava", "The Long Fall",
            "Killed by molten rock.",
            "Death", null, TriggerType.FirstEvent, "death_lava", 1,
            RewardType.Col, 50, null, 0, null, false),
        new("hubris", "Hubris",
            "Died within five turns of leveling up.",
            "Death", null, TriggerType.Conditional, "hubris", 1,
            RewardType.Col, 200, null, 0, null, false),
        new("ill_prepared", "Ill-Prepared",
            "Died on Floor 1.",
            "Death", null, TriggerType.Conditional, "f1_death", 1,
            RewardType.Col, 100, null, 0, null, false),
        new("death_by_boss", "Bested by a Boss",
            "Killed by a floor boss.",
            "Death", null, TriggerType.FirstEvent, "death_boss", 1,
            RewardType.Col, 100, null, 0, null, false),

        // ────────────────────────────────────────────────────────────────
        //   Equipment compositions — checked via Conditional triggers on
        //   equip events. Drives the Equipment tab view.
        // ────────────────────────────────────────────────────────────────
        new("eq_black_swordsman", "Black Swordsman",
            "Wielded Elucidator and Dark Repulser simultaneously.",
            "Equipment", null, TriggerType.Conditional, "wield_dual_kirito", 1,
            RewardType.EquippableTitle, 0, StatType.Attack, 6, null, true),
        new("eq_sealed_wielder", "Sealed Wielder",
            "Equipped a sealed Divine weapon.",
            "Equipment", null, TriggerType.Conditional, "equip_sealed", 1,
            RewardType.Col, 200, null, 0, null, false),
        new("eq_refined_plus_10", "Master Refiner",
            "Refined any weapon to +10.",
            "Equipment", null, TriggerType.Conditional, "refine_10", 1,
            RewardType.Col, 1000, null, 0, null, false),
        new("eq_legendary_equipped", "Legendary Bearer",
            "Equipped a Legendary weapon for the first time.",
            "Equipment", null, TriggerType.Conditional, "equip_legendary", 1,
            RewardType.Col, 300, null, 0, null, false),
        new("eq_divine_equipped", "Divine Bearer",
            "Equipped a Divine weapon for the first time.",
            "Equipment", null, TriggerType.Conditional, "equip_divine", 1,
            RewardType.Col, 500, null, 0, null, false),

        // ────────────────────────────────────────────────────────────────
        //   Canon callbacks.
        // ────────────────────────────────────────────────────────────────
        new("canon_beater", "The Beater",
            "Cleared Floor 1 alone, with no party members.",
            "Canon", null, TriggerType.Conditional, "f1_solo_clear", 1,
            RewardType.Col, 500, null, 0, null, false),
        new("canon_invincible", "Invincible",
            "Defeated the Floor 99 boss.",
            "Canon", null, TriggerType.FloorReached, null, 99,
            RewardType.EquippableTitle, 0, StatType.Defense, 5, null, true),
        new("canon_iron_man", "Iron Man",
            "Cleared Aincrad without dying once.",
            "Canon", null, TriggerType.Conditional, "no_death_clear", 1,
            RewardType.EquippableTitle, 0, StatType.Vitality, 10, null, true),

        // ────────────────────────────────────────────────────────────────
        //   Discovery — Bestiary thresholds.
        // ────────────────────────────────────────────────────────────────
        new("bestiary_25", "Bestiary Apprentice", "Encounter 25 monster types.",
            "Discovery", null, TriggerType.BestiaryCount, null, 25,
            RewardType.Col, 250, null, 0, null, false),
        new("bestiary_50", "Bestiary Scholar", "Encounter 50 monster types.",
            "Discovery", null, TriggerType.BestiaryCount, null, 50,
            RewardType.Col, 500, null, 0, null, false),
        new("bestiary_100", "Bestiary Sage", "Encounter 100 monster types.",
            "Discovery", null, TriggerType.BestiaryCount, null, 100,
            RewardType.Col, 1500, null, 0, null, false),
        new("bestiary_complete", "Aincrad Naturalist",
            "Encounter every monster type in Aincrad.",
            "Discovery", null, TriggerType.BestiaryCount, null, 250,
            RewardType.EquippableTitle, 0, StatType.Intelligence, 6, null, true),

        // ────────────────────────────────────────────────────────────────
        //   Collectables — 184 Legendary entries (DisplayOnly).
        //   SubCategory = canon bucket (LN / AL / IF / HF / LR / MD / FD / Myth / Non-Canon).
        //   SpoilerHidden flagged for canon-spoiler weapons.
        // ────────────────────────────────────────────────────────────────

        // ── One-Handed Sword (37) ───────────────────────────────────────
        new("legendary_elucidator", "Elucidator", "Black sword anchored at F50.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "elucidator", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dark_repulser", "Dark Repulser",
            "Lisbeth-forged blue blade, F55 canon.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "dark_repulser", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_remains_heart", "Remains Heart", "F48 anchor sword.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "remains_heart", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_savage_squall", "Savage Squall", "F17 chest drop.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "savage_squall", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_void_eater", "Void Eater", "F30 chest drop.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "void_eater", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_eurynomes_holy_sword", "Eurynome's Holy Sword",
            "F90 HF holy-tier blade.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "eurynomes_holy_sword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_fiendblade_deathbringer", "Fiendblade Deathbringer",
            "F81 HF demonic-tier blade.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "fiendblade_deathbringer", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_fayblade_tizona", "Fayblade Tizona", "F83 HF fae-tier blade.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "fayblade_tizona", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_godblade_dragonslayer", "Godblade Dragonslayer",
            "F85 HF dragon-tier blade.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "godblade_dragonslayer", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_rosso_forneus", "Crimson Forneus", "F61 IF Rosso line.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "ohs_rosso_forneus", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_yasha_astaroth", "Yasha Astaroth", "F87 IF Yasha line.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "ohs_yasha_astaroth", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_gaou_reginleifr", "Gaou Reginleifr", "F90 IF Gaou line.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "ohs_gaou_reginleifr", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_aurumbrand_hauteclaire", "Aurumbrand Hauteclaire",
            "F92 HF gold-tier blade.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ohs_aurumbrand_hauteclaire", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_velocious_brain", "Velocious Brain", "F80-86 HF speed-tier.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ohs_velocious_brain", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_unfolding_truth_fragrant_olive", "Unfolding Truth: Fragrant Olive",
            "F65 AL Yuuki-arc blade.",
            "Collectables", "AL", TriggerType.LegendaryCollected, "ohs_unfolding_truth_fragrant_olive", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_elucidator_rouge", "Elucidator Rouge", "F98 LR red Elucidator.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "ohs_elucidator_rouge", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_blade_of_the_lightwolf", "Blade of the Lightwolf",
            "F77-83 invented blade.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ohs_blade_of_the_lightwolf", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ohs_illustrious_sword", "Illustrious Sword",
            "F79-85 invented blade.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ohs_illustrious_sword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_celestial_blade", "Celestial Blade", "F88-92 invented blade.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_blade", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_liberator", "Liberator", "F56-60 LN ALF-arc blade.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "liberator", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_final_avalanche", "Final Avalanche", "F45-50 myth-tier blade.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "final_avalanche", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ohs_variable_v_vice", "Variable V Vice", "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ohs_variable_v_vice", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_liberator_astral_legion", "Liberator Astral Legion",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ohs_liberator_astral_legion", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_marginless_blade", "Marginless Blade", "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ohs_marginless_blade", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_red_rose_sword", "Red Rose Sword", "F95 LR rose-tier blade.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "ohs_red_rose_sword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_black_iron_dual_sword_a", "Black Iron Dual Sword (A)",
            "F78-84 AL paired blade.",
            "Collectables", "AL", TriggerType.LegendaryCollected, "ohs_black_iron_dual_sword_a", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_black_iron_dual_sword_b", "Black Iron Dual Sword (B)",
            "F78-84 AL paired blade.",
            "Collectables", "AL", TriggerType.LegendaryCollected, "ohs_black_iron_dual_sword_b", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_sword_of_diva", "Sword of Diva", "F70-76 MD song-tier blade.",
            "Collectables", "MD", TriggerType.LegendaryCollected, "ohs_sword_of_diva", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_chaos_raider_dual", "Chaos Raider Dual",
            "F86-92 FD paired blade.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "ohs_chaos_raider_dual", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_golden_osmanthus", "Golden Osmanthus", "F74-80 FD blade.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "ohs_golden_osmanthus", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_tanquiem", "Tanquiem", "F70-76 FD blade.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "ohs_tanquiem", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_silvery_ruler", "Silvery Ruler", "F97 FD blade.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "ohs_silvery_ruler", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_scorching_blade", "Scorching Blade",
            "F69-75 invented fire blade.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ohs_scorching_blade", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ohs_double_edged_blade", "Double-Edged Blade",
            "F71-77 invented blade.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ohs_double_edged_blade", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ohs_dragoncrest", "Dragoncrest", "F84-90 invented dragon blade.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ohs_dragoncrest", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ohs_blazing_sword", "Blazing Sword", "F66-72 LR fire blade.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "ohs_blazing_sword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ohs_rainbow_blade_ex_eterna", "Rainbow Blade Ex Eterna",
            "F90-95 LR rainbow blade.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "ohs_rainbow_blade_ex_eterna", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Two-Handed Sword (20) ───────────────────────────────────────
        new("legendary_saintblade_durandal", "Saintblade Durandal", "F87 HF saint-tier sword.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "saintblade_durandal", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_stigmablade_arondight", "Stigmablade Arondight",
            "F95 HF stigma-tier sword.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "stigmablade_arondight", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_demonblade_gram", "Demonblade Gram", "F96 HF demon-tier sword.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "demonblade_gram", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_sacred_cross", "Sacred Cross", "F92 LN cross-tier greatsword.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "ths_sacred_cross", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_wice_ritter", "Wice Ritter", "F86-92 IF knight-tier greatsword.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "ths_wice_ritter", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_demonslayer", "Demonslayer", "F82-88 invented greatsword.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ths_demonslayer", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_celestial_greatsword", "Celestial Greatsword",
            "F94-98 invented greatsword.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_greatsword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ifrit", "Ifrit", "F50-58 myth-tier greatsword.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "ifrit", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_demonblade_crimson_stream", "Demonblade Crimson Stream",
            "F40 invented greatsword.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "demonblade_crimson_stream", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ths_saintblade_ragnarok", "Saintblade Ragnarok",
            "F92-98 HF saint-tier sword.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ths_saintblade_ragnarok", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_absoludia_avatar", "Absoludia (Avatar)",
            "F70-100 HF avatar-pool greatsword.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ths_absoludia_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_ogreblade_over_the_cross", "Ogreblade: Over the Cross",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ths_ogreblade_over_the_cross", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_deliverer_majestic_lord", "Deliverer: Majestic Lord",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ths_deliverer_majestic_lord", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_ambitious_juggernaut", "Ambitious Juggernaut",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ths_ambitious_juggernaut", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_sword_of_causality", "Sword of Causality",
            "F62-68 MD causality blade.",
            "Collectables", "MD", TriggerType.LegendaryCollected, "ths_sword_of_causality", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_flame_lord", "Flame Lord", "F80 FD flame-tier sword.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "ths_flame_lord", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ths_blazewyrm_greatsword", "Blazewyrm Greatsword",
            "F75-82 invented greatsword.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ths_blazewyrm_greatsword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ths_purgatorial_greatsword", "Purgatorial Greatsword",
            "F86-92 invented greatsword.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ths_purgatorial_greatsword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ths_lifestream_greatsword", "Lifestream Greatsword",
            "F88-94 invented greatsword.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "ths_lifestream_greatsword", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_ths_object_eraser", "Object Eraser", "F89-95 LR object-tier sword.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "ths_object_eraser", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Katana (20) ─────────────────────────────────────────────────
        new("legendary_jato_onikirimaru", "Jato Onikirimaru", "F80 HF oni-tier katana.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "jato_onikirimaru", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_shinto_ama_no_murakumo", "Shinto Ama-no-Murakumo",
            "F95 HF myth-tier katana.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "shinto_ama_no_murakumo", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_yato_masamune", "Yato Masamune", "F98 HF demon-tier katana.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "yato_masamune", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_muramasa", "Muramasa", "F90-94 LN cursed-tier katana.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "kat_muramasa", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_saku", "Saku", "F94 LN katana.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "kat_saku", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_demon_blade_muramasa", "Demon Blade Muramasa",
            "F65-72 LR muramasa lineage.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "kat_demon_blade_muramasa", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_midnight_sun", "Midnight Sun", "F49 invented katana.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "midnight_sun", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_celestial_katana", "Celestial Katana", "F89-93 invented katana.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_katana", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_shichishito", "Shichishito (Seven-Branched Sword)",
            "F55-62 myth-tier katana.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "shichishito", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_kat_yasha_oratorio", "Yasha Oratorio", "F85-90 IF Yasha lineage.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "kat_yasha_oratorio", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_gaou_oratorio", "Gaou Oratorio", "F88-94 IF Gaou lineage.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "kat_gaou_oratorio", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_burning_haze_avatar", "Burning Haze (Avatar)",
            "F70-100 HF avatar-pool katana.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "kat_burning_haze_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_godslayer_tattered_hope", "Godslayer: Tattered Hope",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "kat_godslayer_tattered_hope", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_avidya_samsara_blade", "Avidya Samsara Blade",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "kat_avidya_samsara_blade", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_shining_nemesisz", "Shining Nemesisz",
            "F66-72 MD shining-tier katana.",
            "Collectables", "MD", TriggerType.LegendaryCollected, "kat_shining_nemesisz", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_murasama_g4_dual", "Murasama G4 Dual",
            "F88-94 FD paired katana.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "kat_murasama_g4_dual", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_spirit_kagutsuchi", "Spirit: Kagutsuchi",
            "F60 FD spirit-tier katana.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "kat_spirit_kagutsuchi", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_spirit_susanoo", "Spirit: Susanoo",
            "F70 FD spirit-tier katana.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "kat_spirit_susanoo", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_futsu_no_mitama", "Futsu-no-Mitama", "F60-66 LR myth katana.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "kat_futsu_no_mitama", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_kat_darkness_rending_blade", "Darkness-Rending Blade",
            "F84-90 LR dark-tier katana.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "kat_darkness_rending_blade", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Rapier (17) ─────────────────────────────────────────────────
        new("legendary_mothers_rosario", "Mother's Rosario", "F76 Yuuki canon rapier.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "mothers_rosario", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_rosso_rhapsody", "Rosso Rhapsody", "F58-64 IF Rosso rapier.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "rap_rosso_rhapsody", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_spiralblade_rendering_fail", "Spiralblade Rendering Fail",
            "F84 HF spiral-tier rapier.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "rap_spiralblade_rendering_fail", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_glimmerblade_banishing_ray", "Glimmerblade Banishing Ray",
            "F93 HF glimmer-tier rapier.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "rap_glimmerblade_banishing_ray", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_midnight_rain", "Midnight Rain", "F43 invented rapier.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "midnight_rain", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_celestial_rapier", "Celestial Rapier", "F91-95 invented rapier.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_rapier", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_lambent_light", "Lambent Light", "F40 Asuna canon rapier.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "lambent_light", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_charadrios", "Charadrios", "F45-52 myth-tier rapier.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "charadrios", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_radiant_light", "Radiant Light", "F88-94 LN late-Asuna rapier.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "radiant_light", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_ishvalca_avatar", "Ishvalca (Avatar)",
            "F70-100 HF avatar-pool rapier.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "rap_ishvalca_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_championfoil_radiant_chariot", "Championfoil: Radiant Chariot",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "rap_championfoil_radiant_chariot", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_glimmerspine_silver_bullet", "Glimmerspine Silver Bullet",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "rap_glimmerspine_silver_bullet", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_noctis_strasse", "Noctis Strasse", "F84-90 LN night-tier rapier.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "rap_noctis_strasse", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_espada_of_sword_dance", "Espada of Sword Dance",
            "F60-66 MD dance-tier rapier.",
            "Collectables", "MD", TriggerType.LegendaryCollected, "rap_espada_of_sword_dance", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_macafitel", "Macafitel", "F85 FD rapier.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "rap_macafitel", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_rap_graceful_needle", "Graceful Needle",
            "F86-92 invented rapier.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "rap_graceful_needle", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_rap_glaring_light", "Glaring Light", "F77-83 LR light-tier rapier.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "rap_glaring_light", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Axe (17) ────────────────────────────────────────────────────
        new("legendary_axe_ground_gorge", "Ground Gorge", "F55 HF earth-tier axe.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "axe_ground_gorge", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_ragnaroks_bane_headsman", "Ragnarok's Bane: Headsman",
            "F94 HF executioner-tier axe.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "ragnaroks_bane_headsman", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_rosso_dominion", "Rosso Dominion", "F58-64 IF Rosso axe.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "axe_rosso_dominion", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_crusher_bond_cyclone", "Crusher: Bond Cyclone",
            "F85 HF cyclone-tier axe.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "axe_crusher_bond_cyclone", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_fellaxe_demons_scythe", "Fellaxe: Demon's Scythe",
            "F86 HF demon-tier axe.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "axe_fellaxe_demons_scythe", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_celestial_axe", "Celestial Axe", "F65-72 invented axe.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_axe", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_nidhoggs_fang", "Nidhogg's Fang", "F58-65 myth-tier axe.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "nidhoggs_fang", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_axe_lord_burster_avatar", "Lord Burster (Avatar)",
            "F70-100 HF avatar-pool axe.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "axe_lord_burster_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_hecatomb_giga_disaster", "Hecatomb: Giga Disaster",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "axe_hecatomb_giga_disaster", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_ingurgitator_belzericht", "Ingurgitator: Belzericht",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "axe_ingurgitator_belzericht", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_schwarzs_blitz", "Schwarz's Blitz", "F88-94 LN black-tier axe.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "axe_schwarzs_blitz", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_northern_light", "Northern Light", "F96 LN ice-tier axe.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "axe_northern_light", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_naz", "Naz", "F86-92 FD axe.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "axe_naz", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_axe_deathbringer", "Deathbringer", "F88-94 invented axe.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "axe_deathbringer", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_axe_snowsunder", "Snowsunder", "F66-72 invented ice axe.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "axe_snowsunder", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_axe_lang", "Lang", "F44-48 LR low-tier axe.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "axe_lang", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_axe_nadr", "Nadr", "F73-79 LR mid-tier axe.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "axe_nadr", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Mace (14) ───────────────────────────────────────────────────
        new("legendary_yggdrasil", "Yggdrasil", "F62-68 myth-tier mace.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "yggdrasil", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_mace_of_asclepius", "Mace of Asclepius",
            "F77 HF healer-tier mace.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "mace_of_asclepius", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_infinite_ouroboros", "Infinite Ouroboros",
            "F79 HF ouroboros-tier mace.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "infinite_ouroboros", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_starmace_elysium", "Starmace Elysium",
            "F88 HF starlight-tier mace.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "starmace_elysium", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_mce_caduceus", "Caduceus", "F70-76 LR healer-tier mace.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "mce_caduceus", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_cactus_bludgeon", "Cactus Bludgeon", "F38 invented mace.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "cactus_bludgeon", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_celestial_mace", "Celestial Mace", "F62-68 invented mace.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_mace", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_mce_ijelfur_avatar", "Ijelfur (Avatar)",
            "F70-100 HF avatar-pool mace.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "mce_ijelfur_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_mce_dictators_punisher", "Dictator's Punisher",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "mce_dictators_punisher", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_mce_photon_hammer_xp_smasher", "Photon Hammer: XP Smasher",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "mce_photon_hammer_xp_smasher", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_mce_grida_replicant", "Grida Replicant", "F75-81 FD mace.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "mce_grida_replicant", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_mce_starshatter", "Starshatter", "F75-81 invented mace.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "mce_starshatter", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_mce_beasthowl", "Beasthowl", "F70-76 invented mace.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "mce_beasthowl", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_mce_whirlpool_hammer", "Whirlpool Hammer", "F80-86 invented mace.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "mce_whirlpool_hammer", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),

        // ── Spear (15) ──────────────────────────────────────────────────
        new("legendary_vijaya", "Vijaya", "F60-67 myth-tier spear.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "vijaya", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_demonspear_gae_bolg", "Demonspear Gáe Bolg",
            "F83 HF demon-tier spear.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "demonspear_gae_bolg", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_saintspear_rhongomyniad", "Saintspear Rhongomyniad",
            "F91 HF saint-tier spear.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "saintspear_rhongomyniad", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_godspear_gungnir", "Godspear Gungnir",
            "F98 HF god-tier spear.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "godspear_gungnir", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_spr_lunatic_roof", "Lunatic Roof", "F98 LN top-tier spear.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "spr_lunatic_roof", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_spr_wave_schneider", "Wave Schneider", "F92-96 LN water-tier spear.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "spr_wave_schneider", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_spr_divine_laevateinn", "Divine Laevateinn",
            "F86-92 LR fire-tier spear.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "spr_divine_laevateinn", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_celestial_spear", "Celestial Spear", "F93-97 invented spear.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_spear", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_spr_rosso_sigrun", "Rosso Sigrun", "F58-64 IF Rosso spear.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "spr_rosso_sigrun", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_spr_asleigeon_avatar", "Asleigeon (Avatar)",
            "F70-100 HF avatar-pool spear.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "spr_asleigeon_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_spr_heavenslance_elpis_order", "Heavenslance: Elpis Order",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "spr_heavenslance_elpis_order", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_spr_arctic_pillar", "Arctic Pillar", "F78-84 invented spear.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "spr_arctic_pillar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_spr_frostpeak", "Frostpeak", "F84-90 invented spear.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "spr_frostpeak", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_spr_brave_song", "Brave Song", "F72-78 LR song-tier spear.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "spr_brave_song", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_spr_elders_trident", "Elder's Trident", "F73-79 LR trident.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "spr_elders_trident", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Dagger (14) ─────────────────────────────────────────────────
        new("legendary_mate_chopper", "Mate Chopper", "F1-5 IF starter dagger.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "mate_chopper", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_misericorde", "Misericorde", "F50-58 myth-tier dagger.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "misericorde", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_dag_rue_feuille", "Rue Feuille", "F94-98 LN late-tier dagger.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "dag_rue_feuille", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dag_mirage_knife", "Mirage Knife", "F95 LN mirage-tier dagger.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "dag_mirage_knife", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dag_obsidian_dagger", "Obsidian Dagger", "F70-76 FD dagger.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "dag_obsidian_dagger", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dag_thunder_gods_rift_blade", "Thunder God's Rift Blade",
            "F78-84 FD thunder-tier dagger.",
            "Collectables", "FD", TriggerType.LegendaryCollected, "dag_thunder_gods_rift_blade", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dag_fragarach", "Fragarach", "F76-82 LR retribution dagger.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "dag_fragarach", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_phantasmagoria", "Phantasmagoria", "F24 invented dagger.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "phantasmagoria", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_celestial_dagger", "Celestial Dagger", "F70-76 invented dagger.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_dagger", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_dag_yasha_envy", "Yasha Envy", "F85-90 IF Yasha dagger.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "dag_yasha_envy", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dag_genocide_avatar", "Genocide (Avatar)",
            "F70-100 HF avatar-pool dagger.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "dag_genocide_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dag_notes_end_trinity", "Notes End: Trinity",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "dag_notes_end_trinity", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_dag_whitespark", "Whitespark", "F86-92 invented dagger.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "dag_whitespark", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_dag_giardino", "Giardino", "F25-47 LR garden-tier dagger.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "dag_giardino", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),

        // ── Bow (11) ────────────────────────────────────────────────────
        new("legendary_bow_zephyros", "Zephyros", "F85 LN wind-tier bow.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "bow_zephyros", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_bow_artemis", "Artemis", "F99 LN top-tier bow.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "bow_artemis", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_bow_rosso_albatross", "Rosso Albatross", "F58-64 IF Rosso bow.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "bow_rosso_albatross", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_bow_silvan_bow", "Silvan Bow", "F69-75 LR forest-tier bow.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "bow_silvan_bow", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_bow_holy_larc_qui_ne_faut", "Holy: L'Arc Qui Ne Faut",
            "F89-95 LR holy-tier bow.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "bow_holy_larc_qui_ne_faut", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_starfall", "Starfall", "F11 invented bow.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "starfall", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_celestial_bow", "Celestial Bow", "F96-99 invented bow.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_bow", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_bow_cinder_bow", "Cinder Bow", "F73-79 invented fire bow.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "bow_cinder_bow", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_bow_loveblight_bow", "Loveblight Bow", "F80-86 invented bow.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "bow_loveblight_bow", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_bow_glitzwood_bow", "Glitzwood Bow", "F84-90 invented bow.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "bow_glitzwood_bow", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_bow_artemis_fult", "Artemis Fult", "F73-79 LR Artemis lineage.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "bow_artemis_fult", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Scimitar (10) ───────────────────────────────────────────────
        new("legendary_iblis", "Iblis", "F45-52 myth-tier scimitar.",
            "Collectables", "Myth", TriggerType.LegendaryCollected, "iblis", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_sci_arcaneblade_soul_binder", "Arcaneblade: Soul Binder",
            "F80 HF arcane-tier scimitar.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "sci_arcaneblade_soul_binder", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_sci_fellblade_ruinous_doom", "Fellblade: Ruinous Doom",
            "F83 HF fell-tier scimitar.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "sci_fellblade_ruinous_doom", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_sci_deathglutton_epetamu", "Deathglutton: Epetamu",
            "F99 HF endgame scimitar.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "sci_deathglutton_epetamu", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_sci_silver_wing", "Silver Wing", "F92-96 LN silver-tier scimitar.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "sci_silver_wing", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_sci_glow_haze", "Glow Haze", "F93 LN glow-tier scimitar.",
            "Collectables", "LN", TriggerType.LegendaryCollected, "sci_glow_haze", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_celestial_scimitar", "Celestial Scimitar",
            "F65-71 invented scimitar.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_scimitar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_sci_saphir_avatar", "Saphir (Avatar)",
            "F70-100 HF avatar-pool scimitar.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "sci_saphir_avatar", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_sci_crescentblade_original_sin", "Crescentblade: Original Sin",
            "F48 HF Lindarth craft.",
            "Collectables", "HF", TriggerType.LegendaryCollected, "sci_crescentblade_original_sin", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_sci_savage_sandstorm", "Savage Sandstorm",
            "F75-81 invented scimitar.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "sci_savage_sandstorm", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),

        // ── Shield (4) ──────────────────────────────────────────────────
        new("legendary_shd_rosso_aegis", "Rosso Aegis", "F61 IF Rosso shield.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "shd_rosso_aegis", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_shd_yasha_kavacha", "Yasha Kavacha", "F87 IF Yasha shield.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "shd_yasha_kavacha", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_shd_gaou_tatari", "Gaou Tatari", "F90 IF Gaou shield.",
            "Collectables", "IF", TriggerType.LegendaryCollected, "shd_gaou_tatari", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_shd_ancile", "Ancile", "F84-90 LR roman-tier shield.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "shd_ancile", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Scythe (2) ──────────────────────────────────────────────────
        new("legendary_celestial_scythe", "Celestial Scythe", "F70-76 invented scythe.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_scythe", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_scy_eldark_radius_sigma", "Eldark Radius Sigma",
            "F48 LR Lindarth craft.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "scy_eldark_radius_sigma", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Claws (3) ───────────────────────────────────────────────────
        new("legendary_clw_iron_fist_oguma", "Iron Fist Oguma",
            "F77-83 LR fist-tier claws.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "clw_iron_fist_oguma", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),
        new("legendary_celestial_claws", "Celestial Claws", "F66-72 invented claws.",
            "Collectables", "Non-Canon", TriggerType.LegendaryCollected, "celestial_claws", 1,
            RewardType.DisplayOnly, 0, null, 0, null, false),
        new("legendary_clw_paopei", "Paopei", "F73-79 LR mythic claws.",
            "Collectables", "LR", TriggerType.LegendaryCollected, "clw_paopei", 1,
            RewardType.DisplayOnly, 0, null, 0, null, true),

        // ── Collection threshold milestones ─────────────────────────────
        new("collect_25", "Collector",
            "Collected 25 Legendary weapons.",
            "Collectables", null, TriggerType.CollectableCount, null, 25,
            RewardType.Col, 500, null, 0, null, false),
        new("collect_50", "Avid Collector",
            "Collected 50 Legendary weapons.",
            "Collectables", null, TriggerType.CollectableCount, null, 50,
            RewardType.Col, 1500, null, 0, null, false),
        new("collect_100", "Legendary Hunter",
            "Collected 100 Legendary weapons.",
            "Collectables", null, TriggerType.CollectableCount, null, 100,
            RewardType.Col, 5000, null, 0, null, false),
        new("collect_184", "Aincrad Archive",
            "Collected every Legendary weapon in Aincrad.",
            "Collectables", null, TriggerType.CollectableCount, null, 184,
            RewardType.EquippableTitle, 0, StatType.Intelligence, 5, null, false),
    };

    public static readonly IReadOnlyDictionary<string, Milestone> ById =
        All.ToDictionary(m => m.Id);
}
